name: GuideConverter
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch pushed to'     
        required: true
        default: 'refs/heads/master'
      guide_name:
        description: 'Guide changed'
        required: true
        default: 'guide-rest-intro'
        
jobs:
  printBranch:
    runs-on: ubuntu-latest

    steps: 

      - name: Output message
        run: |
          echo "${{ github.event.inputs.branch }}"
          echo "${{ github.event.inputs.guide_name }}"
          
  convertMaster:
    name: Make PR to Master
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.branch, 'master') || contains(github.event.inputs.branch, 'main') || contains(github.event.inputs.branch, 'prod')
  
    steps:

      # Any prerequisite steps
      - uses: actions/checkout@master
        
      - name: Checkout Guide Converter repo
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/cloud-hosted-guide-converter
          path: GuideConverter
        
      - name: Checkout guide repo
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/${{ github.event.inputs.guide_name }}
          path: GuideConverter/${{ github.event.inputs.guide_name }}
        
      - name: Checkout guides-common repo
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/guides-common
          path: GuideConverter/Guides-common

      - uses: actions/setup-java@v1
        with:
          java-version: '15' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      
      - name: Run Converter
        run: |
          branchName=${{ github.event.inputs.branch }}
          git init
          mkdir -p instructions/cloud-hosted-${{ github.event.inputs.guide_name }}/
          rm -f instructions/cloud-hosted-${{ github.event.inputs.guide_name }}/README.md
          cd GuideConverter
          mvn compiler:compile
          mvn exec:java -Dexec.args="${{ github.event.inputs.guide_name }} ${branchName:11}"
          mvn -Dtest=TestConversion test -DguideName="${{ github.event.inputs.guide_name }}"
          rm -f importFunctions.class
          rm -f functions.class
          rm -f CloudHostedGuideConverter.class
          cd ..
          mv GuideConverter/${{ github.event.inputs.guide_name }}.md instructions/cloud-hosted-${{ github.event.inputs.guide_name }}/instructions.md
          rm -rf GuideConverter
          bash .github/workflows/draftRemoval.sh cloud-hosted-${{ github.event.inputs.guide_name }}
          git add .
          git config --global user.email "GuidesBot@OpenLiberty.io"
          git config --global user.name "GuidesBot"
          git commit -m "Updated by github actions from ${{ github.event.inputs.guide_name }}"
          git checkout --ours instructions/cloud-hosted-${{ github.event.inputs.guide_name }}/instructions.md
    
      - uses: peter-evans/create-pull-request@v3
        with:
            title: "To Master: Change to cloud-hosted-${{ github.event.inputs.guide_name }}"
            body: "Updated by github actions, triggered by the ${{ github.event.inputs.guide_name }} repo.  ![Testing-Conversion](https://github.com/OpenLiberty/quick-labs/workflows/Testing-Conversion/badge.svg?branch=master)"
            branch: "cloud-hosted-${{ github.event.inputs.guide_name }}/master"
            base: "master" 
        name: Create Pull Request

  convertStaging:
    name: Make PR to Staging
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.branch, 'qa') || contains(github.event.inputs.branch, 'staging')
  
    steps:

      # Any prerequisite steps
      - uses: actions/checkout@v2
        with:
          ref: staging
        
      - name: Checkout Guide Converter repo
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/cloud-hosted-guide-converter
          path: GuideConverter
        
      - name: Checkout guide repo
        uses: actions/checkout@v2
        with:
          ref: qa
          repository: OpenLiberty/${{ github.event.inputs.guide_name }}
          path: GuideConverter/${{ github.event.inputs.guide_name }}
        
      - name: Checkout guides-common repo
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/guides-common
          path: GuideConverter/Guides-common

      - uses: actions/setup-java@v1
        with:
          java-version: '15' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: Run Converter
        run: |
          branchName=${{ github.event.inputs.branch }}
          git init
          mkdir -p instructions/cloud-hosted-${{ github.event.inputs.guide_name }}/
          rm -f instructions/cloud-hosted-${{ github.event.inputs.guide_name }}/README.md
          cd GuideConverter
          mvn compiler:compile
          mvn exec:java -Dexec.args="${{ github.event.inputs.guide_name }} ${branchName:11}"
          mvn -Dtest=TestConversion test -DguideName="${{ github.event.inputs.guide_name }}"
          rm -f importFunctions.class
          rm -f functions.class
          rm -f CloudHostedGuideConverter.class
          cd ..
          mv GuideConverter/${{ github.event.inputs.guide_name }}.md instructions/cloud-hosted-${{ github.event.inputs.guide_name }}/instructions.md
          rm -rf GuideConverter
          bash .github/workflows/draftRemoval.sh cloud-hosted-${{ github.event.inputs.guide_name }}
          git add .
          git config --global user.email "GuidesBot@OpenLiberty.io"
          git config --global user.name "GuidesBot"
          git commit -m "Updated by github actions from ${{ github.event.inputs.guide_name }}"
          git checkout --ours instructions/cloud-hosted-${{ github.event.inputs.guide_name }}/instructions.md
    
      - uses: peter-evans/create-pull-request@v3
        with:
            title: "To Staging: Change to cloud-hosted-${{ github.event.inputs.guide_name }}"
            body: "Updated by github actions, triggered by the ${{ github.event.inputs.guide_name }} repo.   ![Testing-Conversion](https://github.com/OpenLiberty/quick-labs/workflows/Testing-Conversion/badge.svg?branch=staging)"
            branch: "cloud-hosted-${{ github.event.inputs.guide_name }}/staging"
            base: "staging" 
        name: Create Pull Request


  triggerPostConversionTesting:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Invoke workflow in another repo with inputs
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Testing-Conversion
        token: ${{ secrets.GUIDECONVERSIONTOOL_PASSWORD }}
        inputs: '{ "branch":"${{ github.event.inputs.branch }}" , "cloud-hosted-${{ github.event.inputs.guide_name }}" }'