name: Mirror to Gitlab lab branch
 
# Triggers the workflow on push events but only for the staging branch.
on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    name: Lab Mirror
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix: # Uses an array of Json variables to pass the repo names.
              # The names differ between Github and Gitlab so this is necessary.
              # Add new cloud-hosted-guides here to add them to the mirror process.
              # i.e. {"github":"new-lab-github-url","gitlab":"new-lab-gitlab-url"}
        repo: 
          - {"github":"cloud-hosted-draft-guide-devlab-1","gitlab":"cloud-hosted-draft-guide-devlab-1","gitlab-branch":"lab-204-instruction"}
          - {"github":"cloud-hosted-draft-guide-devlab-2","gitlab":"cloud-hosted-draft-guide-devlab-2","gitlab-branch":"lab-207-instruction"}
          - {"github":"cloud-hosted-guide-arquillian-managed","gitlab":"cloud-hosted-guide-arquillian-managed","gitlab-branch":"lab-103-instruction"}
          - {"github":"cloud-hosted-guide-bean-validation","gitlab":"cloud-hosted-guide-bean-validation","gitlab-branch":"lab-105-instruction"}
          - {"github":"cloud-hosted-guide-cdi-intro","gitlab":"cloud-hosted-guide-cdi-intro","gitlab-branch":"lab-371-instruction"}
          - {"github":"cloud-hosted-guide-containerize","gitlab":"cloud-hosted-guide-containerize","gitlab-branch":"lab-155-instruction"}
          - {"github":"cloud-hosted-guide-contract-testing","gitlab":"cloud-hosted-guide-contract-testing","gitlab-branch":"lab-154-instruction"}
          - {"github":"cloud-hosted-guide-cors","gitlab":"cloud-hosted-guide-cors","gitlab-branch":"lab-102-instruction"}
          - {"github":"cloud-hosted-guide-docker","gitlab":"cloud-hosted-guide-docker","gitlab-branch":"lab-169-instruction"}
          - {"github":"cloud-hosted-guide-getting-started","gitlab":"cloud-hosted-guide-getting-started","gitlab-branch":"lab-138-instruction"}
          - {"github":"cloud-hosted-guide-jpa-intro","gitlab":"cloud-hosted-guide-jpa-intro","gitlab-branch":"lab-101-instruction"}
          - {"github":"cloud-hosted-guide-kubernetes-intro","gitlab":"cloud-hosted-guide-kubernetes-intro","gitlab-branch":"lab-137-instruction"}
          - {"github":"cloud-hosted-guide-kubernetes-microprofile-config","gitlab":"cloud-hosted-guide-kubernetes-microprofile-config","gitlab-branch":"lab-143-instruction"}
          - {"github":"cloud-hosted-guide-kubernetes-microprofile-health","gitlab":"cloud-hosted-guide-kubernetes-microprofile-health","gitlab-branch":"lab-144-instruction"}
          - {"github":"cloud-hosted-guide-maven-intro","gitlab":"cloud-hosted-guide-maven-intro","gitlab-branch":"lab-91-instruction"}
          - {"github":"cloud-hosted-guide-maven-multimodules","gitlab":"cloud-hosted-guide-maven-multimodules","gitlab-branch":"lab-70-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-config","gitlab":"cloud-hosted-guide-microprofile-config","gitlab-branch":"lab-166-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-fallback","gitlab":"cloud-hosted-guide-microprofile-fallback","gitlab-branch":"lab-140-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-health","gitlab":"cloud-hosted-guide-microprofile-health","gitlab-branch":"lab-168-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-jwt","gitlab":"cloud-hosted-guide-microprofile-jwt","gitlab-branch":"lab-165-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-metrics","gitlab":"cloud-hosted-guide-microprofile-metrics","gitlab-branch":"lab-152-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-openapi","gitlab":"cloud-hosted-guide-microprofile-openapi","gitlab-branch":"lab-150-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-opentracing","gitlab":"cloud-hosted-guide-microprofile-opentracing","gitlab-branch":"lab-156-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-opentracing-jaeger","gitlab":"cloud-hosted-guide-microprofile-opentracing-jaeger","gitlab-branch":"lab-153-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-reactive-messaging","gitlab":"cloud-hosted-guide-reactive-messaging","gitlab-branch":"lab-164-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-reactive-messaging-acknowledgment","gitlab":"cloud-hosted-guide-microprofile-reactive-messaging-acknowledgment","gitlab-branch":"lab-159-instruction"}
          - {"github":"cloud-hosted-guide-microprofile-rest-client","gitlab":"cloud-hosted-guide-microprofile-rest-client","gitlab-branch":"lab-139-instruction"}
          - {"github":"cloud-hosted-guide-openliberty-operator-intro","gitlab":"cloud-hosted-guide-openliberty-operator-intro","gitlab-branch":"lab-85-instruction"}
          - {"github":"cloud-hosted-guide-openliberty-operator-openshift","gitlab":"cloud-hosted-guide-openliberty-operator-openshift","gitlab-branch":"lab-21-instruction"}
          - {"github":"cloud-hosted-guide-rest-client-angular","gitlab":"cloud-hosted-guide-rest-client-angular","gitlab-branch":"lab-90-instruction"}
          - {"github":"cloud-hosted-guide-rest-client-angularjs","gitlab":"cloud-hosted-guide-rest-client-angularjs","gitlab-branch":"lab-89-instruction"}
          - {"github":"cloud-hosted-guide-rest-client-java","gitlab":"cloud-hosted-guide-rest-client-java","gitlab-branch":"lab-149-instruction"}
          - {"github":"cloud-hosted-guide-rest-client-reactjs","gitlab":"cloud-hosted-guide-rest-client-reactjs","gitlab-branch":"lab-88-instruction"}
          - {"github":"cloud-hosted-guide-rest-hateoas","gitlab":"cloud-hosted-guide-rest-hateoas","gitlab-branch":"lab-86-instruction"}
          - {"github":"cloud-hosted-guide-rest-intro","gitlab":"cloud-hosted-guide-rest-intro","gitlab-branch":"lab-141-instruction"}
          - {"github":"cloud-hosted-guide-spring-boot","gitlab":"cloud-hosted-guide-spring-boot","gitlab-branch":"lab-110-instruction"}
          - {"github":"cloud-hosted-liberty-deep-dive","gitlab":"cloud-hosted-liberty-deepdive","gitlab-branch":"lab-372-instruction"}

    steps:

    # Any prerequisite steps
    - uses: actions/checkout@master
      with: 
        ref: staging

    # Mirror to Gitlab repo
    - name: Mirror
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@gitlab.com:ibm/skills-network/quicklabs/${{matrix.repo.gitlab}}.git
        BRANCH: ${{matrix.repo.gitlab-branch}}
        FOLDER: instructions/${{matrix.repo.github}}
        MESSAGE: "{msg}" # Sets the commit message on gitlab to be the same as on github.
        SSH_PRIVATE_KEY: ${{secrets.DEPLOY_KEY_QUICK_LABS}}
        KNOWN_HOSTS_FILE: .github/workflows/known_hosts # Needed if target repo is not on github.com.
        SKIP_EMPTY_COMMITS: "true"
    
    # Output link to staged files
    - name: Print gitlab URL
      run: echo "Gitlab url at https://gitlab.com/ibm/skills-network/quicklabs/${{matrix.repo.gitlab}}/-/blob/${{matrix.repo.gitlab-branch}}/instructions.md"
      shell: bash
