name: Testing-Conversion
on: 
  workflow_dispatch:
    inputs:
      guide_name:
        description: 'Guide changed'
        required: true
        default: 'guide-rest-intro'

jobs:
  printBranch:
    runs-on: ubuntu-latest
  
    steps:

    - name: Get Guide name
      run: |
        echo "${{ github.event.inputs.guide_name }}"
        prText="${{ github.event.inputs.guide_name }}"
        removeStart=${prText:44} 
        removeEnd=${removeStart% *}
        echo $removeEnd

  convertMaster:
    name: Make PR to Master
    runs-on: ubuntu-latest
  
    steps:

      # Any prerequisite steps
      - uses: actions/checkout@master
        
      - name: Checkout Guide Converter repo
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/cloud-hosted-guide-converter
          path: GuideConverter
          ref: refs/head/staging